site_name: Портфолио - Потёмкин Платон
nav:
  - Главная: index.md
  - Об авторе: about.md
  - Лабораторные работы:
      - Лабораторная 1: labs/lab1.md
      - Лабораторная 2: labs/lab2.md
      - Лабораторная 3: labs/lab3.md

#site_url: https://ppv.org/portfolio
repo_url: https://github.com/platonpotemkin51-source/
edit_uri: edit/main/source/docs/
theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - content.action.edit
  language: ru
  palette:
    scheme: default
    primary: grey
    accent: light blue
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil-box
    view: material/eye

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search
  - git-revision-date-localized:
      type: datetime
      locale: ru
